FROM jeanblanchard/busybox-java:8 
MAINTAINER Jeganathan Swaminathan <jegan@tektutor.org>

COPY tektutor-customer-ms-0.0.1-SNAPSHOT.jar /

EXPOSE 8085

ENTRYPOINT [ "java", "-jar", "/tektutor-customer-ms-0.0.1-SNAPSHOT.jar"] 

