
package com.amdocs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RPNCalculator", targetNamespace = "http://amdocs.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RPNCalculator {


    /**
     * 
     * @param rpnMathExpression
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "evaluateReturn", targetNamespace = "http://amdocs.com")
    @RequestWrapper(localName = "evaluate", targetNamespace = "http://amdocs.com", className = "com.amdocs.Evaluate")
    @ResponseWrapper(localName = "evaluateResponse", targetNamespace = "http://amdocs.com", className = "com.amdocs.EvaluateResponse")
    public double evaluate(
        @WebParam(name = "rpnMathExpression", targetNamespace = "http://amdocs.com")
        String rpnMathExpression);

}
