FROM ubuntu
MAINTAINER Jeganathan Swaminathan <jegan@tektutor.org>

#ENV http_proxy http://192.168.101.52:8080
#ENV https_proxy http://192.168.101.52:8080
#ENV no_proxy_hosts localhost,127.0.0.1,your-machine-ip

RUN apt-get update && apt-get install default-jdk git -y
RUN apt-get maven -y
